### ISSUE TITLE
The hive problem..

### ISSUE THREAD

**Issue by Chest3r14** [weslambert/alert2#1]
Hello Wes,

I have some issues with extracting data from security onion to thehive. I am using your script with the configuration files, but nothing happens. There is connectivity between the onion and the hive and with a post request (the hive api) I can create a case. So probably the problem is the script, in my opinion. I am trying to execute it with data input by me and there aren't any errors. Still, no case is created.
TheHive version - 3.1.0
This is how I am testing it:
python e2hive_case.py "-t" "sometitle", "-d" "somedescription", "-s" "2" from cli in my security onion. I tried it from another test machine, still nothing and no error reported.
This is the script e2hive_case.py, not modified:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#!/usr/bin/python
# Modified from script by Keith Taylor, found here:
# http://informationonsecurity.blogspot.com/2015/10/automating-forensic-artifact-collection.html
import json, urllib2, base64, requests
import requests
import argparse
import sys
from ConfigParser import SafeConfigParser

parser = SafeConfigParser()
parser.read('/etc/elastalert/rules/e2hive.conf')

url = parser.get('config', 'url')
apikey = parser.get('config', 'apikey')

sys.stdout = open('/tmp/e2hive.log', 'w')

parser = argparse.ArgumentParser(description='Post a case to the Hive')
parser.add_argument('-t','--title', help='Title',required=True)
parser.add_argument('-d','--description',help='Description', required=True)
parser.add_argument('-s','--severity',help='Severity', required=False)
args = parser.parse_args()

title = args.title
description = args.description
severity = args.severity

authheader =  "Bearer" + apikey
headers = {
    "Authorization": authheader,
    "Content-Type": "application/json"
}

data = {
  "title": title,
  "description": description,
  "severity": int(severity)
}

response = requests.post(url + "/api/case",
                          headers=headers, data=json.dumps(data)
                        )
print response.content
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Here is the conf file e2hive.conf:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[config]
url = AddressOfHivePlusPort
apikey = SomeKey
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The apikey works with a normal request, like:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curl -XPOST -H 'Authorization: Bearer SomeKey' -H 'Content-Type: application/json' AddressOfHivePlusPort/api/case -d '{
"title": "My first case",
  "description": "This case has been created by my custom script"
}'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The files are in same directory.. Maybe it's because of the new version of TheHive or something else. I don't know..
I am not sure where to open such a request, but I hope you will see it and advice me.
Thanks in advance,
Antony

**Comment by weslambert** [comment]
Hi Anthony,

I'll have to take a look at this and let you know what I find.  

Thanks,
Wes

**Comment by weslambert** [comment]
@Chest3r14 ,

It works for me without issue.

Please try the following:

`sudo python e2hive_case.py -t "Test Case 1" -d "this is only a test!" -s "2"`

You'll want to make sure you have the config file in the correct spot as well, and that the script is pointing to the correct location.

**Comment by Chest3r14** [comment]
Hello Wes,

Still, there is no case in thehive.. The script executes, but nothing happens. When I tcpdump on thehive, I see that traffic is coming but for some reason, no case is created.

All my files are in /etc/elastalert/rules/ and I am sure that the account can make cases, because with a normal curl post I can create a case. I tried on different machines with no progress. There is connectivity between the machines.

Where can I be wrong? What may be the cause of this problem, in your opinion?
Again, thank you and sorry for taking your time with such an individual problem, but I have no idea why it doesn't work.

**Comment by Chest3r14** [comment]
Ok, I checked the log the script makes in /tmp/e2hive.log:
{"type":"AuthenticationError","message":"Authentication failure"}

Still I will show you my conf file:
[config]
url = http://10.20.1.95:9000
apikey = sx4YRpVl6FN6SFwy1gd9a7KZgMeUgoLS
It's OK, it is not external. I tried with / in the end of the url. but then there is another error - //api/case..
I think the script reads the config file, because it connects with thehive, but for some reason the apikey is not accepted..

**Comment by Chest3r14** [comment]
Hey again,

This if from application.log in thehive:

2018-10-12 10:36:37,693 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-22 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Only bearer authentication is supported
        basic: AuthenticationError Only basic authentication is supported
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-12 10:36:37,694 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-22 - POST /api/case returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:241)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-10-12 10:38:37,853 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-18 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Only bearer authentication is supported
        basic: AuthenticationError Only basic authentication is supported
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-12 10:38:37,854 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-18 - POST /api/case returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:241)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-10-12 10:39:38,162 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-6 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Only bearer authentication is supported
        basic: AuthenticationError Only basic authentication is supported
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-12 10:39:38,163 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-6 - POST /api/case returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:241)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2018-10-12 10:40:37,856 [ERROR] from org.elastic4play.controllers.Authenticated in application-akka.actor.default-dispatcher-3 - Authentication failure:
        session: AuthenticationError User session not found
        pki: AuthenticationError Certificate authentication is not configured
        key: AuthenticationError Only bearer authentication is supported
        basic: AuthenticationError Only basic authentication is supported
        init: AuthenticationError Use of initial user is forbidden because users exist in database
2018-10-12 10:40:37,857 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-3 - POST /api/case returned 401
org.elastic4play.AuthenticationError: Authentication failure
        at org.elastic4play.controllers.Authenticated.$anonfun$getContext$4(Authenticated.scala:241)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I tried with different user, I revoked the key, made another one, still no success..

**Comment by weslambert** [comment]
Hi @Chest3r14 

What version of TheHive are you using?

Thanks,
Wes

**Comment by Chest3r14** [comment]
TheHive3.1.0
Elastic4Play1.6.2
Play2.6.18
Elastic4s5.6.6
ElasticSearch5.6.9
CORTEX
cortex - 2.1.1 (OK)

**Comment by weslambert** [comment]
This still works for me using a fresh install of the latest version(s):

````
TheHive3.1.1
Elastic4Play1.6.3
Play2.6.18
Elastic4s5.6.6
ElasticSearch5.6.9
CORTEX
LOCAL CORTEX - 2.1.1 (OK)
````

Maybe try updating to the latest to see if it helps.

**Comment by Chest3r14** [comment]
Hello Wes,

I have reinstalled the system and now it is working OK. I guess some packets weren't installed or something else but with the latest version of thehive all is working.

Thank you for the help and the support.
